name: build standalone application

on:
  push:
    tags:
      - v*

permissions:
  contents: write

concurrency:
  group: build-standalone-${{ github.head_ref }}

jobs:
  build:
    name: Build standalone 3DFin windows version
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add private key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.DENDROMATICS_GITHUB_DEPLOY_KEY }}

      - name: Install Hatch
        run: python -m pip install hatch

      - name: Build standalone
        run: hatch build -t custom

      - name: Add to release page
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/3DFin.exe
