name: build standalone

on:
  push
    # should only build standalone when a new version is tagged
    # tags:
    # - 3DFin-v*

permissions:
  contents: write

concurrency:
  group: build-standalone-${{ github.head_ref }}

jobs:
  build:
    name: Build standalone 3DFon windows version
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add private key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
                        ${{ secrets.PIP_DEPLOY }}

    - name: Install Hatch
      run: python -m pip install hatch
    
    - name: Build standalone
      run: hatch run pyinstaller:build

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist/3DFin.exe
        if-no-files-found: error

  publish:
    name: Publish release
    needs:
    - build
    runs-on: windows-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: dist

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/3DFin.exe